export let navbar = [
    {
        "role":"user",
        "name":"Dashboard",
        "link":"/home",
    },
    {
        "role":"user",
        "name":"Games",
        "link":"/home",
    },
    {
        "role":"user",
        "name":"Home",
        "link":"/home",
    },
    {
        "role":"user",
        "name":"Forum",
        "link":"/home",
    },
]